/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface IAnkrRateProviderInterface extends utils.Interface {
  functions: {
    "averagePercentageRate(address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "averagePercentageRate"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "averagePercentageRate",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "averagePercentageRate",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IAnkrRateProvider extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IAnkrRateProviderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    averagePercentageRate(
      addr: string,
      day: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  averagePercentageRate(
    addr: string,
    day: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    averagePercentageRate(
      addr: string,
      day: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    averagePercentageRate(
      addr: string,
      day: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    averagePercentageRate(
      addr: string,
      day: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
