/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAlgebraPoolState,
  IAlgebraPoolStateInterface,
} from "../IAlgebraPoolState";

const _abi = [
  {
    type: "function",
    name: "activeIncentive",
    inputs: [],
    outputs: [
      {
        name: "virtualPool",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "globalState",
    inputs: [],
    outputs: [
      {
        name: "price",
        type: "uint160",
        internalType: "uint160",
      },
      {
        name: "tick",
        type: "int24",
        internalType: "int24",
      },
      {
        name: "fee",
        type: "uint16",
        internalType: "uint16",
      },
      {
        name: "timepointIndex",
        type: "uint16",
        internalType: "uint16",
      },
      {
        name: "communityFeeToken0",
        type: "uint8",
        internalType: "uint8",
      },
      {
        name: "communityFeeToken1",
        type: "uint8",
        internalType: "uint8",
      },
      {
        name: "unlocked",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "liquidity",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint128",
        internalType: "uint128",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "liquidityCooldown",
    inputs: [],
    outputs: [
      {
        name: "cooldownInSeconds",
        type: "uint32",
        internalType: "uint32",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "positions",
    inputs: [
      {
        name: "key",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "liquidityAmount",
        type: "uint128",
        internalType: "uint128",
      },
      {
        name: "lastLiquidityAddTimestamp",
        type: "uint32",
        internalType: "uint32",
      },
      {
        name: "innerFeeGrowth0Token",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "innerFeeGrowth1Token",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "fees0",
        type: "uint128",
        internalType: "uint128",
      },
      {
        name: "fees1",
        type: "uint128",
        internalType: "uint128",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tickTable",
    inputs: [
      {
        name: "wordPosition",
        type: "int16",
        internalType: "int16",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ticks",
    inputs: [
      {
        name: "tick",
        type: "int24",
        internalType: "int24",
      },
    ],
    outputs: [
      {
        name: "liquidityTotal",
        type: "uint128",
        internalType: "uint128",
      },
      {
        name: "liquidityDelta",
        type: "int128",
        internalType: "int128",
      },
      {
        name: "outerFeeGrowth0Token",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "outerFeeGrowth1Token",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "outerTickCumulative",
        type: "int56",
        internalType: "int56",
      },
      {
        name: "outerSecondsPerLiquidity",
        type: "uint160",
        internalType: "uint160",
      },
      {
        name: "outerSecondsSpent",
        type: "uint32",
        internalType: "uint32",
      },
      {
        name: "initialized",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "timepoints",
    inputs: [
      {
        name: "index",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "initialized",
        type: "bool",
        internalType: "bool",
      },
      {
        name: "blockTimestamp",
        type: "uint32",
        internalType: "uint32",
      },
      {
        name: "tickCumulative",
        type: "int56",
        internalType: "int56",
      },
      {
        name: "secondsPerLiquidityCumulative",
        type: "uint160",
        internalType: "uint160",
      },
      {
        name: "volatilityCumulative",
        type: "uint88",
        internalType: "uint88",
      },
      {
        name: "averageTick",
        type: "int24",
        internalType: "int24",
      },
      {
        name: "volumePerLiquidityCumulative",
        type: "uint144",
        internalType: "uint144",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalFeeGrowth0Token",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalFeeGrowth1Token",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class IAlgebraPoolState__factory {
  static readonly abi = _abi;
  static createInterface(): IAlgebraPoolStateInterface {
    return new utils.Interface(_abi) as IAlgebraPoolStateInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAlgebraPoolState {
    return new Contract(address, _abi, signerOrProvider) as IAlgebraPoolState;
  }
}
