/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISynthereumLiquidityPoolGeneral,
  ISynthereumLiquidityPoolGeneralInterface,
} from "../ISynthereumLiquidityPoolGeneral";

const _abi = [
  {
    type: "function",
    name: "collateralToken",
    inputs: [],
    outputs: [
      {
        name: "collateralCurrency",
        type: "address",
        internalType: "contract IERC20Upgradeable",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "synthereumFinder",
    inputs: [],
    outputs: [
      {
        name: "finder",
        type: "address",
        internalType: "contract ISynthereumFinder",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "syntheticToken",
    inputs: [],
    outputs: [
      {
        name: "syntheticCurrency",
        type: "address",
        internalType: "contract IERC20Upgradeable",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "syntheticTokenSymbol",
    inputs: [],
    outputs: [
      {
        name: "symbol",
        type: "string",
        internalType: "string",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "version",
    inputs: [],
    outputs: [
      {
        name: "poolVersion",
        type: "uint8",
        internalType: "uint8",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class ISynthereumLiquidityPoolGeneral__factory {
  static readonly abi = _abi;
  static createInterface(): ISynthereumLiquidityPoolGeneralInterface {
    return new utils.Interface(
      _abi
    ) as ISynthereumLiquidityPoolGeneralInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISynthereumLiquidityPoolGeneral {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ISynthereumLiquidityPoolGeneral;
  }
}
