/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace OptimizedVaultsRegistry {
  export type ClaimableRewardsInfoStruct = {
    flywheel: string;
    vault: string;
    rewardToken: string;
    rewardTokenName: string;
    rewardTokenSymbol: string;
    rewardTokenDecimals: BigNumberish;
    rewards: BigNumberish;
  };

  export type ClaimableRewardsInfoStructOutput = [
    string,
    string,
    string,
    string,
    string,
    number,
    BigNumber
  ] & {
    flywheel: string;
    vault: string;
    rewardToken: string;
    rewardTokenName: string;
    rewardTokenSymbol: string;
    rewardTokenDecimals: number;
    rewards: BigNumber;
  };

  export type AdapterInfoStruct = {
    adapter: string;
    allocation: BigNumberish;
    market: string;
    pool: string;
  };

  export type AdapterInfoStructOutput = [string, BigNumber, string, string] & {
    adapter: string;
    allocation: BigNumber;
    market: string;
    pool: string;
  };

  export type VaultInfoStruct = {
    vault: string;
    asset: string;
    assetSymbol: string;
    assetDecimals: BigNumberish;
    estimatedTotalAssets: BigNumberish;
    apr: BigNumberish;
    adaptersCount: BigNumberish;
    isEmergencyStopped: boolean;
    performanceFee: BigNumberish;
    depositFee: BigNumberish;
    withdrawalFee: BigNumberish;
    managementFee: BigNumberish;
    adaptersData: OptimizedVaultsRegistry.AdapterInfoStruct[];
  };

  export type VaultInfoStructOutput = [
    string,
    string,
    string,
    number,
    BigNumber,
    BigNumber,
    BigNumber,
    boolean,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    OptimizedVaultsRegistry.AdapterInfoStructOutput[]
  ] & {
    vault: string;
    asset: string;
    assetSymbol: string;
    assetDecimals: number;
    estimatedTotalAssets: BigNumber;
    apr: BigNumber;
    adaptersCount: BigNumber;
    isEmergencyStopped: boolean;
    performanceFee: BigNumber;
    depositFee: BigNumber;
    withdrawalFee: BigNumber;
    managementFee: BigNumber;
    adaptersData: OptimizedVaultsRegistry.AdapterInfoStructOutput[];
  };
}

export interface OptimizedVaultsRegistryInterface extends utils.Interface {
  functions: {
    "_acceptOwner()": FunctionFragment;
    "_setPendingOwner(address)": FunctionFragment;
    "addVault(address)": FunctionFragment;
    "getAllVaults()": FunctionFragment;
    "getClaimableRewards(address)": FunctionFragment;
    "getLatestVaultExtensions(address)": FunctionFragment;
    "getVaultsData()": FunctionFragment;
    "initialize()": FunctionFragment;
    "owner()": FunctionFragment;
    "pendingOwner()": FunctionFragment;
    "removeVault(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setEmergencyExit()": FunctionFragment;
    "setLatestVaultExtensions(address,address[])": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "vaults(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "_acceptOwner"
      | "_setPendingOwner"
      | "addVault"
      | "getAllVaults"
      | "getClaimableRewards"
      | "getLatestVaultExtensions"
      | "getVaultsData"
      | "initialize"
      | "owner"
      | "pendingOwner"
      | "removeVault"
      | "renounceOwnership"
      | "setEmergencyExit"
      | "setLatestVaultExtensions"
      | "transferOwnership"
      | "vaults"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_acceptOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_setPendingOwner",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "addVault", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getAllVaults",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimableRewards",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestVaultExtensions",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultsData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "removeVault", values: [string]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setEmergencyExit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLatestVaultExtensions",
    values: [string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "vaults",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "_acceptOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_setPendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimableRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestVaultExtensions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultsData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEmergencyExit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLatestVaultExtensions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaults", data: BytesLike): Result;

  events: {
    "Initialized(uint8)": EventFragment;
    "NewOwner(address,address)": EventFragment;
    "NewPendingOwner(address,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewOwner"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewPendingOwner"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface NewOwnerEventObject {
  oldOwner: string;
  newOwner: string;
}
export type NewOwnerEvent = TypedEvent<[string, string], NewOwnerEventObject>;

export type NewOwnerEventFilter = TypedEventFilter<NewOwnerEvent>;

export interface NewPendingOwnerEventObject {
  oldPendingOwner: string;
  newPendingOwner: string;
}
export type NewPendingOwnerEvent = TypedEvent<
  [string, string],
  NewPendingOwnerEventObject
>;

export type NewPendingOwnerEventFilter = TypedEventFilter<NewPendingOwnerEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface OptimizedVaultsRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OptimizedVaultsRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _acceptOwner(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    _setPendingOwner(
      newPendingOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    addVault(
      vault: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getAllVaults(overrides?: CallOverrides): Promise<[string[]]>;

    getClaimableRewards(
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getLatestVaultExtensions(
      vault: string,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getVaultsData(
      overrides?: CallOverrides
    ): Promise<
      [OptimizedVaultsRegistry.VaultInfoStructOutput[]] & {
        vaultsData: OptimizedVaultsRegistry.VaultInfoStructOutput[];
      }
    >;

    initialize(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pendingOwner(overrides?: CallOverrides): Promise<[string]>;

    removeVault(
      vault: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setEmergencyExit(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setLatestVaultExtensions(
      vault: string,
      extensions: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    vaults(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;
  };

  _acceptOwner(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  _setPendingOwner(
    newPendingOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  addVault(
    vault: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getAllVaults(overrides?: CallOverrides): Promise<string[]>;

  getClaimableRewards(
    account: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getLatestVaultExtensions(
    vault: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getVaultsData(
    overrides?: CallOverrides
  ): Promise<OptimizedVaultsRegistry.VaultInfoStructOutput[]>;

  initialize(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  pendingOwner(overrides?: CallOverrides): Promise<string>;

  removeVault(
    vault: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setEmergencyExit(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setLatestVaultExtensions(
    vault: string,
    extensions: string[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  vaults(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    _acceptOwner(overrides?: CallOverrides): Promise<void>;

    _setPendingOwner(
      newPendingOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addVault(vault: string, overrides?: CallOverrides): Promise<boolean>;

    getAllVaults(overrides?: CallOverrides): Promise<string[]>;

    getClaimableRewards(
      account: string,
      overrides?: CallOverrides
    ): Promise<OptimizedVaultsRegistry.ClaimableRewardsInfoStructOutput[]>;

    getLatestVaultExtensions(
      vault: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getVaultsData(
      overrides?: CallOverrides
    ): Promise<OptimizedVaultsRegistry.VaultInfoStructOutput[]>;

    initialize(overrides?: CallOverrides): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    pendingOwner(overrides?: CallOverrides): Promise<string>;

    removeVault(vault: string, overrides?: CallOverrides): Promise<boolean>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setEmergencyExit(overrides?: CallOverrides): Promise<void>;

    setLatestVaultExtensions(
      vault: string,
      extensions: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    vaults(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "NewOwner(address,address)"(
      oldOwner?: null,
      newOwner?: null
    ): NewOwnerEventFilter;
    NewOwner(oldOwner?: null, newOwner?: null): NewOwnerEventFilter;

    "NewPendingOwner(address,address)"(
      oldPendingOwner?: null,
      newPendingOwner?: null
    ): NewPendingOwnerEventFilter;
    NewPendingOwner(
      oldPendingOwner?: null,
      newPendingOwner?: null
    ): NewPendingOwnerEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    _acceptOwner(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    _setPendingOwner(
      newPendingOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    addVault(
      vault: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getAllVaults(overrides?: CallOverrides): Promise<BigNumber>;

    getClaimableRewards(
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getLatestVaultExtensions(
      vault: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVaultsData(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pendingOwner(overrides?: CallOverrides): Promise<BigNumber>;

    removeVault(
      vault: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setEmergencyExit(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setLatestVaultExtensions(
      vault: string,
      extensions: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    vaults(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    _acceptOwner(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    _setPendingOwner(
      newPendingOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    addVault(
      vault: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getAllVaults(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getClaimableRewards(
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getLatestVaultExtensions(
      vault: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVaultsData(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeVault(
      vault: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setEmergencyExit(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setLatestVaultExtensions(
      vault: string,
      extensions: string[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    vaults(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
