import {
  AssetRiskIL,
  AssetRiskLiquidity,
  AssetRiskMktCap,
  AssetRiskSupply,
  ERC4626Strategy,
  PlatformRiskAdminWithTimelock,
  PlatformRiskAudit,
  PlatformRiskContractsVerified,
  PlatformRiskReputation,
  Strategy,
  StrategyComplexity,
  StrategyTimeInMarket,
} from "@ionicprotocol/types";

export const strategies: ERC4626Strategy[] = [
  // {
  //   address: "0x23bBcF59BF843cD55c4DA9bDB81429695C87f847",
  //   strategy: Strategy.DotDot,
  //   name: "DotDot 2brl",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.BATTLE_TESTED,
  //   riskIL: AssetRiskIL.NONE,
  //   liquidity: AssetRiskLiquidity.HIGH,
  //   mktCap: AssetRiskMktCap.LARGE,
  //   supplyCentralised: AssetRiskSupply.CENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0x643fd5AB2485dF7D9Ad43C4c210AbEc8Ae7e44D8",
  //   strategy: Strategy.Beefy,
  //   name: "Beefy EPS BNBx/BNB  Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.BATTLE_TESTED,
  //   riskIL: AssetRiskIL.LOW,
  //   liquidity: AssetRiskLiquidity.HIGH,
  //   mktCap: AssetRiskMktCap.LARGE,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0xBCAc816440f7ef66Fea896b307352b86a83F94E8",
  //   strategy: Strategy.Beefy,
  //   name: "Beefy 2brl",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.BATTLE_TESTED,
  //   riskIL: AssetRiskIL.NONE,
  //   liquidity: AssetRiskLiquidity.HIGH,
  //   mktCap: AssetRiskMktCap.MEDIUM,
  //   supplyCentralised: AssetRiskSupply.CENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0xac99ced1a1310fB04618d4801888120ccDD7B87B",
  //   strategy: Strategy.Beefy,
  //   name: "Beefy BNBx-BNB LP vault Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.BATTLE_TESTED,
  //   riskIL: AssetRiskIL.NONE,
  //   liquidity: AssetRiskLiquidity.HIGH,
  //   mktCap: AssetRiskMktCap.MEDIUM,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0x369ddC01E8feF7350Eb740f4a32647E8640F0A17",
  //   strategy: Strategy.HelioHAY,
  //   name: "HAY Staking Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.NEW,
  //   riskIL: AssetRiskIL.NONE,
  //   liquidity: AssetRiskLiquidity.LOW,
  //   mktCap: AssetRiskMktCap.LARGE,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.NEW,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0x33395bbe8fcA14368003f9aCE2Deb0Ba5103c670",
  //   strategy: Strategy.Beefy,
  //   name: "Beefy sAMM jBRL-BRZ LP Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.BATTLE_TESTED,
  //   riskIL: AssetRiskIL.NONE,
  //   liquidity: AssetRiskLiquidity.HIGH,
  //   mktCap: AssetRiskMktCap.LARGE,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0xE141ce7507656f9b2c45d06d649961Eb84e19f82",
  //   strategy: Strategy.ThenaERC4626,
  //   name: "Thena vAMM-HAY-ankrBNB LP Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.NEW,
  //   riskIL: AssetRiskIL.HIGH,
  //   liquidity: AssetRiskLiquidity.HIGH,
  //   mktCap: AssetRiskMktCap.MEDIUM,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0x52156377Dbe031706cfAb4e759cA102e58A19953",
  //   strategy: Strategy.ThenaERC4626,
  //   name: "Thena vAMM-ANKR-HAY LP Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.NEW,
  //   riskIL: AssetRiskIL.HIGH,
  //   liquidity: AssetRiskLiquidity.HIGH,
  //   mktCap: AssetRiskMktCap.MEDIUM,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0x0c0e8ED68a72c31E657Ce5F03A615FB96753C9b5",
  //   strategy: Strategy.ThenaERC4626,
  //   name: "Thena vAMM-ANKR-ankrBNB LP Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.NEW,
  //   riskIL: AssetRiskIL.HIGH,
  //   liquidity: AssetRiskLiquidity.HIGH,
  //   mktCap: AssetRiskMktCap.MEDIUM,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0x02706A482fc9f6B20238157B56763391a45bE60E",
  //   strategy: Strategy.ThenaERC4626,
  //   name: "Thena sAMM-HAY-BUSD LP Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.NEW,
  //   riskIL: AssetRiskIL.NONE,
  //   liquidity: AssetRiskLiquidity.HIGH,
  //   mktCap: AssetRiskMktCap.LARGE,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0xDbC22fE3F4aAE46bA4509b4e13b200E87375b5ab",
  //   strategy: Strategy.ThenaERC4626,
  //   name: "Thena Gamma ankrBNB-ANKR Wide LP Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.NEW,
  //   riskIL: AssetRiskIL.HIGH,
  //   liquidity: AssetRiskLiquidity.LOW,
  //   mktCap: AssetRiskMktCap.LARGE,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0x7A5D376F717732C65d5ac63Fd05F73a287324B05",
  //   strategy: Strategy.ThenaERC4626,
  //   name: "Thena Gamma ankrBNB-ANKR Narrow LP Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.NEW,
  //   riskIL: AssetRiskIL.HIGH,
  //   liquidity: AssetRiskLiquidity.LOW,
  //   mktCap: AssetRiskMktCap.LARGE,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0x3FCA4C8D345340Ef47a698f96e4813e8c4f6076C",
  //   strategy: Strategy.Beefy,
  //   name: "Beefy sAMM stkBNB-WBNB LP Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.BATTLE_TESTED,
  //   riskIL: AssetRiskIL.NONE,
  //   liquidity: AssetRiskLiquidity.HIGH,
  //   mktCap: AssetRiskMktCap.LARGE,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0x7D6679bDbD5E23833F11B777Fd55275a104aD8e5",
  //   strategy: Strategy.Beefy,
  //   name: "Beefy aWBNB-stkBNB Gamma LP Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.BATTLE_TESTED,
  //   riskIL: AssetRiskIL.NONE,
  //   liquidity: AssetRiskLiquidity.HIGH,
  //   mktCap: AssetRiskMktCap.LARGE,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0x3cDB6f8b8bDAEB684d917A3973D737220aE2292a",
  //   strategy: Strategy.Beefy,
  //   name: "Beefy aWBNB-BTCB Gamma Narrow LP Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.BATTLE_TESTED,
  //   riskIL: AssetRiskIL.LOW,
  //   liquidity: AssetRiskLiquidity.HIGH,
  //   mktCap: AssetRiskMktCap.LARGE,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0xFd25A63B7e387a79f9aa28272530DcEe5Efa2FBC",
  //   strategy: Strategy.Beefy,
  //   name: "Beefy aWBNB-ETH Gamma Narrow LP Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.BATTLE_TESTED,
  //   riskIL: AssetRiskIL.LOW,
  //   liquidity: AssetRiskLiquidity.HIGH,
  //   mktCap: AssetRiskMktCap.LARGE,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0xE706134f898320dc1b1772362566bA6646C569c1",
  //   strategy: Strategy.Beefy,
  //   name: "Beefy aWBNB-RDNT Gamma Narrow LP Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.BATTLE_TESTED,
  //   riskIL: AssetRiskIL.HIGH,
  //   liquidity: AssetRiskLiquidity.LOW,
  //   mktCap: AssetRiskMktCap.MEDIUM,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0x2841f61C4D0Dd34010a3E75241c1C80AFc99D202",
  //   strategy: Strategy.Beefy,
  //   name: "Beefy aWBNB-RDNT Gamma Wide LP Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.BATTLE_TESTED,
  //   riskIL: AssetRiskIL.HIGH,
  //   liquidity: AssetRiskLiquidity.LOW,
  //   mktCap: AssetRiskMktCap.MEDIUM,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0x5bEb4BD2164D286CdE9c672910c548dF643a2Caa",
  //   strategy: Strategy.Beefy,
  //   name: "Beefy aWBNB-THE Gamma Narrow LP Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.BATTLE_TESTED,
  //   riskIL: AssetRiskIL.HIGH,
  //   liquidity: AssetRiskLiquidity.LOW,
  //   mktCap: AssetRiskMktCap.MEDIUM,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0xbe79A4B9Cb6892ae0d383038C6e7b25fF79FBc14",
  //   strategy: Strategy.Beefy,
  //   name: "Beefy aWBNB-THE Gamma Wide LP Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.BATTLE_TESTED,
  //   riskIL: AssetRiskIL.HIGH,
  //   liquidity: AssetRiskLiquidity.LOW,
  //   mktCap: AssetRiskMktCap.MEDIUM,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // // POLYGON
  {
    address: "0x72c528B63Ced4a3DF5Ae6e983568566f1Ee7Ad77",
    strategy: Strategy.Beefy,
    name: "Beefy USDR-DAI sLP vault Vault",
    complexity: StrategyComplexity.LOW,
    timeInMarket: StrategyTimeInMarket.BATTLE_TESTED,
    riskIL: AssetRiskIL.NONE,
    liquidity: AssetRiskLiquidity.LOW,
    mktCap: AssetRiskMktCap.MEDIUM,
    supplyCentralised: AssetRiskSupply.DECENTRALIZED,
    reputation: PlatformRiskReputation.ESTABLISHED,
    audit: PlatformRiskAudit.AUDIT,
    contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
    adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  },
  // {
  //   address: "0xc8E8B4A7E0F854Cf516A75fE742FC791dBec9F86",
  //   strategy: Strategy.Beefy,
  //   name: "Beefy jEUR-PAR Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.BATTLE_TESTED,
  //   riskIL: AssetRiskIL.NONE,
  //   liquidity: AssetRiskLiquidity.LOW,
  //   mktCap: AssetRiskMktCap.MEDIUM,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0xdE58CF12595e92ebB07D664eE59A642e360bea58",
  //   strategy: Strategy.Arrakis, // TODO should be called Mimo
  //   name: "Arrakis PAR-USDC Vault",
  //   complexity: StrategyComplexity.MEDIUM,
  //   timeInMarket: StrategyTimeInMarket.EXPERIMENTAL,
  //   riskIL: AssetRiskIL.LOW,
  //   liquidity: AssetRiskLiquidity.LOW,
  //   mktCap: AssetRiskMktCap.MEDIUM,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0xd682451F627d54cfdA74a80972aDaeF133cdc15e",
  //   strategy: Strategy.Arrakis, // TODO should be called Mimo
  //   name: "Balancer LP MIMO80-PAR20",
  //   complexity: StrategyComplexity.MEDIUM,
  //   timeInMarket: StrategyTimeInMarket.EXPERIMENTAL,
  //   riskIL: AssetRiskIL.HIGH,
  //   liquidity: AssetRiskLiquidity.LOW,
  //   mktCap: AssetRiskMktCap.SMALL,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0xdF23f2E94a322685DD4E967dE6165242cf00B85B",
  //   strategy: Strategy.Arrakis,
  //   name: "Arrakis PAR-USDC Vault",
  //   complexity: StrategyComplexity.MEDIUM,
  //   timeInMarket: StrategyTimeInMarket.EXPERIMENTAL,
  //   riskIL: AssetRiskIL.LOW,
  //   liquidity: AssetRiskLiquidity.LOW,
  //   mktCap: AssetRiskMktCap.MEDIUM,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0x36A297A86Eaed6aE0BaEb541F766A1675960B390",
  //   strategy: Strategy.Beefy,
  //   name: "Beefy Balancer JEUR-PAR Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.BATTLE_TESTED,
  //   riskIL: AssetRiskIL.NONE,
  //   liquidity: AssetRiskLiquidity.LOW,
  //   mktCap: AssetRiskMktCap.LARGE,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.NEW,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0x27569756A02Ee590306F1409821b5496A8e4B2B3",
  //   strategy: Strategy.Beefy,
  //   name: "Beefy Balancer MaticX-bba-WMATIC Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.BATTLE_TESTED,
  //   riskIL: AssetRiskIL.NONE,
  //   liquidity: AssetRiskLiquidity.HIGH,
  //   mktCap: AssetRiskMktCap.LARGE,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0x6732E47b15919EaA4a876bC1007bdCa19020d4ED",
  //   strategy: Strategy.Dyson4626,
  //   name: "Dyson Balancer StMatic-bba-WMATIC Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.NEW,
  //   riskIL: AssetRiskIL.NONE,
  //   liquidity: AssetRiskLiquidity.HIGH,
  //   mktCap: AssetRiskMktCap.LARGE,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
  // {
  //   address: "0xb341c397dEe4098c53428bF4f8BC90F79BFDf4bA",
  //   strategy: Strategy.Beefy,
  //   name: "Beefy Curve.fi USDR/DAI/USDC/USDT Vault",
  //   complexity: StrategyComplexity.LOW,
  //   timeInMarket: StrategyTimeInMarket.BATTLE_TESTED,
  //   riskIL: AssetRiskIL.NONE,
  //   liquidity: AssetRiskLiquidity.HIGH,
  //   mktCap: AssetRiskMktCap.LARGE,
  //   supplyCentralised: AssetRiskSupply.DECENTRALIZED,
  //   reputation: PlatformRiskReputation.ESTABLISHED,
  //   audit: PlatformRiskAudit.AUDIT,
  //   contractsVerified: PlatformRiskContractsVerified.CONTRACTS_VERIFIED,
  //   adminWithTimelock: PlatformRiskAdminWithTimelock.ADMIN_WITH_TIMELOCK,
  // },
];
