import "./set-plugin";
import "./admin";
import "./fund";
import "./risk";
import "./upgrade";
import "./upgrade-all";
import "./deploy-dynamic-rewards-market";
import "./deploy-static-rewards-market";
import "./deploy";
