/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IWombatLpAsset__factory } from "./IWombatLpAsset__factory";
export { WombatLpTokenPriceOracle__factory } from "./WombatLpTokenPriceOracle__factory";
