/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DiamondBase__factory } from "./DiamondBase__factory";
export { DiamondExtension__factory } from "./DiamondExtension__factory";
