/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface DIAOracleV2Interface extends utils.Interface {
  functions: {
    "getValue(string)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "getValue"): FunctionFragment;

  encodeFunctionData(functionFragment: "getValue", values: [string]): string;

  decodeFunctionResult(functionFragment: "getValue", data: BytesLike): Result;

  events: {};
}

export interface DIAOracleV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DIAOracleV2Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getValue(
      key: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;
  };

  getValue(
    key: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  callStatic: {
    getValue(
      key: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;
  };

  filters: {};

  estimateGas: {
    getValue(key: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getValue(
      key: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
