/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DIAOracleV2__factory } from "./DIAOracleV2__factory";
export { DiaPriceOracle__factory } from "./DiaPriceOracle__factory";
